services:
  # 1. Express API Service
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/bus-ticket-db
    depends_on:
      - mongo

  # 2. MongoDB Database Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
