import { Router } from "express";
import { userRoute } from "./users.route";
import { busRoute } from "./bus.route";
import { seatRoute } from "./seat.route";
import { merchantDashboardRoute } from "./merchant-dashboard.route";
import AuthHandlers from "../middleware/auth-handler";
import { advertisingRoute } from "./advertising.route";
const appRouter = Router();
appRouter.use("/advertising", advertisingRoute);
appRouter.use(AuthHandlers.requiredAuth);
appRouter.use("/users", userRoute);
appRouter.use("/buses", busRoute);
appRouter.use("/seats", seatRoute);
appRouter.use("/merchant-dashboard", merchantDashboardRoute);
export default appRouter;
