import { Router } from "express";
import { upload } from "../config/cloudinary";
import { userController } from "../controllers/users.controller";
const routers = Router();
routers.get("/", userController.getMany);
routers.post("/", upload.single("profile"), userController.create);
routers.post("/login", userController.login);
routers.patch("/:id", upload.single("profile"), userController.update);
routers.delete("/:id", userController.delete);
routers.get("/:id", userController.getById);
export const userRoute = routers;
